$('#Navi-Btn-Menu').click(function(){
    $(this).hide();
    $('#Navi-Btn-Close').show();
    $('#Navi-Ls').addClass('navi-ls-show')
})
$('#Navi-Btn-Close').click(function(){
    $(this).hide();
    $('#Navi-Btn-Menu').show();
    $('#Navi-Ls').removeClass('navi-ls-show')
})